apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lofi-focus-hub.fullname" . }}
  labels:
    {{- include "lofi-focus-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lofi-focus-hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lofi-focus-hub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          # THIS IS THE NEW PART
          resources:
            {{- toYaml .Values.resources | nindent 12 }}